- name: Run capture2.js
  env:
    FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
    FIREBASE_PROJECT_ID:            ${{ secrets.FIREBASE_PROJECT_ID }}
    FIREBASE_STORAGE_BUCKET:        ${{ secrets.FIREBASE_STORAGE_BUCKET }}
    FIREBASE_DATABASE_URL:          ${{ secrets.FIREBASE_DATABASE_URL }}
    DEVICE_SCALE_FACTOR:            ${{ github.event.inputs.dsf }}
    DRY_RUN:                        ${{ github.event.inputs.dry_run }}
    CAP_PREFIX:                     actions/${{ github.run_id }}
  run: |
    node -v
    pwd
    ls -al
    if [ -n "${{ github.event.inputs.url }}" ]; then
      node capture2.js --url "${{ github.event.inputs.url }}"
    else
      node capture2.js --keyword "${{ github.event.inputs.keyword }}"
    fi

- name: List capture folder (debug)
  if: always()
  run: |
    echo "== repo root =="
    ls -al
    echo "== captures dir =="
    ls -al captures || true

- name: Upload capture artifacts
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: captures
    path: "**/captures/*.png"
    if-no-files-found: warn
